FROM node:10-alpine

RUN adduser --disabled-password --gecos '' react_user

WORKDIR /home/react_user

COPY package*.json ./

RUN apk add --no-cache --virtual .gyp python make g++ \
    && npm install \
    && npm install -g webpack \
    && apk del .gyp

COPY . .

USER react_user

CMD npm run start